### ISSUE TITLE
Check LogManager needed or use ILogger

### ISSUE THREAD

**Issue by Niyo** [daenetCorporation/DurableTaskMicroservices#13]
At the moment we are using LogManager and ILogger in OrchestrationBase and TaskBase.
We should decide what we want to use and don't mix them.

I am unsure if LogManager is doing anything at moment, didn't saw any init code for LogManager.

**Comment by ddobric** [comment]
We should consider:
1. Removing of LoggingTask.cs. Logging should be implemented inside of every task by using of ILogger.
2. Removing of PrepareLoggingContextTask.cs in the same turn.

**Comment by ddobric** [comment]
Done
