### ISSUE TITLE
Implement Tasks as TaskBase in project Daenet.Microservice.Common.Test

### ISSUE THREAD

**Issue by ddobric** [daenetCorporation/DurableTaskMicroservices#9]
Test orchestration currently uses 

`public class Task1 : TaskActivity<string, Null>`

It should use:

`public class Task1 : TaskBase<..,..l>`

**Comment by Niyo** [comment]
create new input type for task1 and task2 (inherit from taskinput) and pass to the tasks

**Comment by Niyo** [comment]
use ILogger in Task1 and Task2

**Comment by Niyo** [comment]
Done with https://github.com/daenetCorporation/DurableTaskMicroservices/commit/8a6e16a91e0d03397ce584af49262341135370a1
